name: Core Release
run-name: Update helm chart for core release ${{ inputs.tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Core tag (e.g. 16.5.0, without the v prefix)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.repository == 'opf/helm-charts' && inputs.tag != '' && inputs.tag != 'dev'
    name: Update the Helm chart for a core release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.OPENRPOJECTCI_GH_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Configure Git
        run: |
          git config user.name openprojectci
          git config user.email operations+openprojectci@openproject.com

      - name: Bump release information
        run: ruby bin/update_from_core_release "${{ inputs.tag }}"

      - name: Commit release
        run: |
          git add .changeset/*.md
          git add charts/openproject/*.yaml
          git commit -m "Update helm chart for core release ${{ inputs.tag }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.OPENRPOJECTCI_GH_TOKEN }}
